theme = "lokalius-kiro-rio"

padding-x = 13
padding-y = [13, 13]

line-height = 1.3
confirm-before-quit = false

[panel]
margin = [5]
row-gap = 10
column-gap = 15

[cursor]
shape = "beam"
blinking = true
blinking-interval = 800

[title]
content = "{{ ABSOLUTE_PATH }}"

[window]
width = 1300
height = 1100
mode = "Maximized"
opacity = 1.0
blur = true
decorations = "Disabled"
colorspace = "display-p3"

[fonts]
size = 22
family = "UbuntuMono Nerd Font"
# `rio`的字体名称：使用`fc-list`，截取`:`后面的第一个字符串
extras = [{ family = "字魂正文宋楷(商用需授权)" }, { family = "OPPO Sans 4.0" }]
hinting = true
disable-warnings-not-found = true

[navigation]
mode = "Tab"
clickable = false
hide-if-single = false
current-working-directory = true
color-automation = []

[shell]
program = "murex"
args = ["-quiet"]

[bindings]
keys = [
  { key = "q", with = "alt", action = "Quit" },

  { key = "left", with = "control | shift", action = "SelectPrevTab" },
  { key = "right", with = "control | shift", action = "SelectNextTab" },
  { key = "w", with = "control | shift", action = "CloseTab" },
  { key = "1", with = "control | shift", action = "SelectTab(0)" },
  { key = "2", with = "control | shift", action = "SelectTab(1)" },
  { key = "3", with = "control | shift", action = "SelectTab(2)" },
  { key = "4", with = "control | shift", action = "SelectTab(3)" },
  { key = "5", with = "control | shift", action = "SelectTab(4)" },
  { key = "6", with = "control | shift", action = "SelectTab(5)" },
  { key = "7", with = "control | shift", action = "SelectTab(6)" },
  { key = "0", with = "control | shift", action = "SelectTab(7)" },

  { key = "t", with = "control | alt", action = "SplitRight" },
  { key = "w", with = "control | alt", action = "CloseSplitOrTab" },
  { key = "left", with = "control | alt", action = "SelectNextSplit" },
  { key = "right", with = "control | alt", action = "SelectPrevSplit" },

  { key = "=", with = "control | shift", action = "IncreaseFontSize" },
  { key = "-", with = "control | shift", action = "DecreaseFontSize" },
  { key = "c", with = "control | shift", action = "Copy" },
  { key = "v", with = "control | shift", action = "Paste" },
]
